version: 2
build:
  machine:
    java: oraclejdk8
jobs:
    formatting:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Run lint on the Kotlin source files.
            command: ./gradlew lintKotlin
    test:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Run the unit tests.
            command: ./gradlew test
    build:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Assemble the outputs.
            command: ./gradlew assemble

workflows:
    version: 2
    deploy:
      jobs:
        - formatting
        - test:
            requires:
              - formatting
        - build:
            requires:
              - test
              - formatting
